<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\collabora_online\Cool\CoolUtils;
use Drupal\file\Entity\File;
use Drupal\media\Entity\Media;

/**
 * Implements hook_theme().
 *
 * Register a module or theme's theme implementations.
 * The implementations declared by this hook specify how a
 * particular render array is to be rendered as HTML.
 *
 * See: https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Render%21theme.api.php/function/hook_theme
 *
 * If you change this method, clear theme registry and routing
 * table 'drush cc theme-registry' and 'drush cc router'.
 */
function collabora_online_theme($existing, $type, $theme, $path) {

  return [
      'collabora_online' => [
          'render element' => 'children',
          'template' => 'collabora-online',
          'path' => $path . '/templates',
          'variables' => [
              'wopiSrc' => 'http://localhost:9980/',
              'message1' => 'Default',
          ],
      ],
      'collabora_online_full' => [
          'template' => 'collabora-online-full',
          'path' => $path . '/templates',
          'variables' => [
              'accessToken' => 'test',
              'wopiSrc' => '/wopi/files/123',
              'wopiClient' => 'https://localhost:9980/',
          ],
      ],
  ];

}

/**
 * Implements hook_entity_operation().
 */
function collabora_online_entity_operation(EntityInterface $entity) {
    if (($entity->getEntityTypeId() != "media") ||
        ($entity->getSource()->getPluginId() != "file")) {
        return [];
    }

    $media = $entity;

    $account = \Drupal::currentUser()->getAccount();
    if (!$entity->access("view", $account)) {
        return [];
    }

    $file = CoolUtils::getFile($media);
    $type = CoolUtils::getDocumentType($file);

    if ($type == NULL) {
        return [];
    }

    $entries = [
        'collabora_online_view' => [
            'title' => t("View in Collabora Online"),
            'weight' => 50,
            'url' => CoolUtils::getEditorUrl($media, false),
        ]
    ];

    if (CoolUtils::canEdit($media) && $media->access("update", $account)) {
        $entries['collabora_online_edit'] = [
            'title' => t("Edit in Collabora Online"),
            'weight' => 50,
            'url' => CoolUtils::getEditorUrl($media, true),
        ];
    }

    return $entries;
}
