<?php
/*
 * Copyright the Collabora Online contributors.
 *
 * SPDX-License-Identifier: MPL-2.0
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\collabora_online\Cool\CoolUtils;
use Drupal\file\Entity\File;
use Drupal\media\Entity\Media;

/**
 * Implements hook_theme().
 *
 * Register a module or theme's theme implementations.  The
 * implementations declared by this hook specify how a particular
 * render array is to be rendered as HTML.
 *
 * See:
 * https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Render%21theme.api.php/function/hook_theme
 *
 * If you change this method, clear theme registry and routing table
 * 'drush cc theme-registry' and 'drush cc router'.
 */
function collabora_online_theme($existing, $type, $theme, $path) {

  return [
      'collabora_online' => [
          'render element' => 'children',
          'template' => 'collabora-online',
          'path' => $path . '/templates',
          'variables' => [
              'accessToken' => 'test',
              'accessTokenTtl' => '86400',
              'iFrameStyle' => 'width:95%;',
              'closebutton' => '',
              'allowfullscreen' => '',
              'wopiSrc' => 'http://localhost:9980/',
              'wopiClient' => 'https://localhost:9980/',
          ],
      ],
      // This is the template for the field preview
      'collabora_online_preview' => [
          'render element' => 'children',
          'template' => 'collabora-online-preview',
          'path' => $path . '/templates',
          'variables' => [
              'editorUrl' => 'about:blank',
              'fileName' => '',
          ],
      ],
      // This is the template for the complete page with embedding.
      'collabora_online_full' => [
          'template' => 'collabora-online-full',
          'path' => $path . '/templates',
          'variables' => [
              'accessToken' => 'test',
              'accessTokenTtl' => '86400',
              'iFrameStyle' => '',
              'closebutton' => '',
              'allowfullscreen' => '',
              'wopiSrc' => '/wopi/files/123',
              'wopiClient' => 'https://localhost:9980/',
          ],
      ],
  ];

}

/**
 * Implements hook_entity_operation().
 *
 * This is used to add the menu entry in the Media content to
 * open the viewer/editor directly.
 */
function collabora_online_entity_operation(EntityInterface $entity) {
    if (($entity->getEntityTypeId() != "media") ||
        ($entity->getSource()->getPluginId() != "file")) {
        return [];
    }

    $media = $entity;

    $account = \Drupal::currentUser()->getAccount();
    if (!$entity->access("view", $account)) {
        return [];
    }

    $file = CoolUtils::getFile($media);
    $type = CoolUtils::getDocumentType($file);

    if ($type == NULL) {
        return [];
    }

    $entries = [
        'collabora_online_view' => [
            'title' => t("View in Collabora Online"),
            'weight' => 50,
            'url' => CoolUtils::getEditorUrl($media, false),
        ]
    ];

    if (CoolUtils::canEdit($file) && $media->access("update", $account)) {
        $entries['collabora_online_edit'] = [
            'title' => t("Edit in Collabora Online"),
            'weight' => 50,
            'url' => CoolUtils::getEditorUrl($media, true),
        ];
    }

    return $entries;
}
